//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileworxApp.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FileworxAppEntities1 : DbContext
    {
        public FileworxAppEntities1()
            : base("name=FileworxAppEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusinessObject> BusinessObjects { get; set; }
        public virtual DbSet<FXCategory> FXCategories { get; set; }
        public virtual DbSet<FXClass> FXClasses { get; set; }
        public virtual DbSet<FXFile> FXFiles { get; set; }
        public virtual DbSet<FXnew> FXnews { get; set; }
        public virtual DbSet<FXPhoto> FXPhotoes { get; set; }
        public virtual DbSet<FXUser> FXUsers { get; set; }
    }
}
