//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileworxObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessObject
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CreationDate { get; set; }
        public string LastModifier { get; set; }
        public int ClassID { get; set; }
    
        public virtual FXClass FXClass { get; set; }
        public virtual FXUser FXUser { get; set; }
        public virtual BusinessObject BusinessObject1 { get; set; }
        public virtual BusinessObject BusinessObject2 { get; set; }
        public virtual FXFile FXFile { get; set; }
        public virtual FXUser FXUser1 { get; set; }
    }
}
