//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileworxObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class FXnew
    {
        public string ID { get; set; }
        public Nullable<int> Category { get; set; }
    
        public virtual FXCategory FXCategory { get; set; }
        public virtual FXFile FXFile { get; set; }
    }
}
