//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileworxApp
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class BusinessObject
    {
        public string ID { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string CreationDate { get; set; }
        public int ClassID { get; set; }
    
        public virtual FXClass FXClass { get; set; }


        public void Create()
        {
            Guid id = Guid.NewGuid();
            using (var context = new FileworxAppEntities())
            {
                var x = new BusinessObject
                {
                    ID = ID,
                    Description = Description,
                    Title = Title,
                    Body = Body,
                    CreationDate = CreationDate,
                    ClassID = ClassID,
                };
                context.BusinessObjects.Add(x);
                context.SaveChanges();
            }
        }
        public BusinessObject Read()
        {
            using (FileworxAppEntities entities = new FileworxAppEntities())
            {

                var obj = (from p in entities.BusinessObjects
                             where p.ID == ID
                             select p).FirstOrDefault();
                return obj;
            }

        }
        public List<BusinessObject> Run()
        {
            using (FileworxAppEntities entities = new FileworxAppEntities())
            {

                var obj = from p in entities.BusinessObjects
                            select p;
                return obj.ToList();
            }

        }
        public void Update()
        {
            using (var db = new FileworxAppEntities())
            {
                (from p in db.BusinessObjects where p.ID == ID select p).ToList().ForEach(x => x.Title = Title);
                (from p in db.BusinessObjects where p.ID == ID select p).ToList().ForEach(x => x.Description = Description);
                (from p in db.BusinessObjects where p.ID == ID select p).ToList().ForEach(x => x.Body = Body);
                (from p in db.BusinessObjects where p.ID == ID select p).ToList().ForEach(x => x.ClassID = ClassID);
                db.SaveChanges();
            }
        }
        public void Delete()
        {
            using (var db = new FileworxAppEntities())
            {
                var obj = (from p in db.BusinessObjects
                            where p.ID == ID
                            select p).FirstOrDefault();

                db.BusinessObjects.Remove(obj);
                db.SaveChanges();

            }
        }
    }
}
